
project_id = "flrdluhakpnuffozgcne"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 5432

[storage]
enabled = true

[auth]
enabled = true
additional_redirect_urls = ["https://localhost:3000"]
site_url = "http://localhost:3000"
