// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flrdluhakpnuffozgcne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscmRsdWhha3BudWZmb3pnY25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNzU4NzYsImV4cCI6MjA1Nzc1MTg3Nn0.ubOjmQYt8c3KQXCwbJLct42cEovQvw0S3TYTUROwENs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);